language: php
php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then NTESTER_FLAGS="phpdbg --coverage ./coverage.xml --coverage-src ./src"; else TESTER_FLAGS=""; fi


after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then
    wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    && php coveralls.phar --verbose --config tests/.coveralls.yml
    || true;
    fi

script:
  - ./tests/run-tests $NTESTER_FLAGS
